{% set name = "adrt" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70970076bc53100901687c7aaad6d4da920c0aec5f0e32da6d446400e539b881

build:
  number: 0
  script:
    - export ADRT_ADDED_CFLAGS='-O3 -flto -fopenmp -fvisibility=hidden -fvisibility-inlines-hidden -fno-math-errno'  # [unix]
    - export CFLAGS="$CFLAGS $ADRT_ADDED_CFLAGS"  # [unix]
    - export CXXFLAGS="$CXXFLAGS $ADRT_ADDED_CFLAGS"  # [unix]
    - export CPPFLAGS="$CPPFLAGS -O3 -DNDEBUG"  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - pip
    - setuptools >=62.6.0
    - numpy
  run:
    - python

test:
  imports:
    - adrt
  requires:
    - pip
    - pytest
    - more-itertools
    - scipy
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
    - python -c "import adrt; assert adrt.core.threading_enabled()"  # [unix]

about:
  home: https://github.com/karlotness/adrt
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - LICENSE_windows.txt  # [win]
  summary: Fast approximate discrete Radon transform for NumPy arrays
  description: |
    This library provides an implementation of an approximate discrete
    Radon transform (ADRT) and its inverse, as a Python module
    operating on NumPy arrays.
  doc_url: https://adrt.readthedocs.io/
  dev_url: https://github.com/karlotness/adrt

extra:
  recipe-maintainers:
    - karlotness
    - dsrim
